### ISSUE TITLE
Re-engineering request on habitat

### ISSUE THREAD

**Issue by johnbeve** [biomedontology/idobru#4]
In IDOBRU, _habitat_ is defined textually as a spatial region, but is nevertheless a subclass of _site_. Additionally, _habitat_ is imported from ENVO, but the term as it is used in IDOBRU has been deprecated in ENVO. 
The most recent version of ENVO - uploaded this year - has _habitat_ as a _material entity_, defined textually as: An environmental system which can sustain and allow the growth of an ecological population. 

It may be worth considering re-engineering to align with the updated ENVO.

**Comment by linikujp** [comment]
This term was imported from IDO. Maybe IDO needs some engineering work.
We will delete this term as for now.

**Comment by johnbeve** [comment]
I think it may have been imported from an older version of IDO, and used from an older version of ENVO. I didn't have that term in any of the IDO files I received a couple of months ago. In any event, I agree IDO needs some engineering too.
